export const SET_DETAILS = "SET_DETAILS";
export const RESET_RECIPE_FORM = "RESET_RECIPE_FORM";
export const ADD_LIST_INPUT = "ADD_LIST_INPUT";
export const SET_LIST_INPUT = "SET_LIST_INPUT";
export const REMOVE_LIST_INPUT = "REMOVE_LIST_INPUT";
export const REPLACE_LIST = "REPLACE_LIST";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const TOGGLE_CATEGORY = "TOGGLE_CATEGORY";

export const REPLACE_RECIPES = "REPLACE_RECIPES";
export const ADD_RECIPE = "ADD_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";

export const FETCH_RECIPES = "FETCH_RECIPES";
export const STORE_RECIPE = "STORE_RECIPE";
export const EDIT_STORED_RECIPE = "EDIT_STORED_RECIPE";
export const DELETE_STORED_RECIPE = "DELETE_STORED_RECIPE";

export const LOADING_ON = "LOADING_ON";
export const LOADING_OFF = "LOADING_OFF";
export const DATA_FETCHED = "DATA_FETCHED";
